#!/usr/bin/env bash
# Fetches mainnet block headers and prints them as Motoko hex constants
# suitable for pasting into test/fixtures/Fixtures.mo.
#
# Usage:
#   ./scripts/fetch-headers.sh 0 1 2 3 4 5 6 7 8 9 10 100000 2014 2015 2016 2017
#
# Source: https://blockstream.info/api/  (public, no auth, rate-limited)
set -euo pipefail

emit() {
  local h=$1
  local hash header
  hash=$(curl -sf "https://blockstream.info/api/block-height/${h}")
  header=$(curl -sf "https://blockstream.info/api/block/${hash}/header")
  printf '  public let H_%d : Text =\n    "%s";\n' "$h" "$header"
}

echo "// Auto-generated by scripts/fetch-headers.sh -- do not edit by hand."
echo "module {"
for h in "$@"; do emit "$h"; done
echo "}"
